### PR TITLE
adding alert_grouping_parameters to service object

### PR DESCRIPTION
**Pull request by kilianw**
Adding alert_grouping_parameters to service definition.

alert_grouping field got changed to 'computed: true' in the schema due to inconsistent naming when using content based routing i.e. 'rules' vs 'content_based'

### CODE REVIEW

**Comment by stmcallister** [comment]
Thanks for adding this @kilianw ! Will you also add a test for the new `alert_group_parameters` field?

**Comment by kilianw** [comment]
Integration test 'TestAccPagerDutyService_AlertContentGrouping' added separately to 'TestAccPagerDutyService_AlertGrouping' as it was failing due to HTTP 500 errors from PD.

**Comment by stmcallister** [comment]
@kilianw It looks like `TestAccPagerDutyService_AlertContentGrouping` works. 🎉  However, now all the other Service tests are not passing. I think all it needs is a `Computed: true` on `alert_grouping_parameters`. Will you get the other Service related tests to also pass? Thanks!

**Comment by kilianw** [comment]
test output:

make testacc TEST=./pagerduty/ TESTARGS='-run=TestAccPagerDutyService*'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./pagerduty/ -v -run=TestAccPagerDutyService* -timeout 120m
=== RUN   TestAccPagerDutyServiceDependency_import
--- PASS: TestAccPagerDutyServiceDependency_import (21.65s)
=== RUN   TestAccPagerDutyServiceEventRule_import
--- PASS: TestAccPagerDutyServiceEventRule_import (14.43s)
=== RUN   TestAccPagerDutyServiceIntegration_import
--- PASS: TestAccPagerDutyServiceIntegration_import (16.09s)
=== RUN   TestAccPagerDutyService_import
--- PASS: TestAccPagerDutyService_import (13.42s)
=== RUN   TestAccPagerDutyServiceWithIncidentUrgency_import
--- PASS: TestAccPagerDutyServiceWithIncidentUrgency_import (13.57s)
=== RUN   TestAccPagerDutyServiceEventRule_Basic
2021/06/30 12:02:11 DestroyEdgeTransformer: pruning unused resource node pagerduty_user.foo (prepare state)
2021/06/30 12:02:11 DestroyEdgeTransformer: pruning unused resource node pagerduty_escalation_policy.foo (prepare state)
2021/06/30 12:02:11 DestroyEdgeTransformer: pruning unused resource node pagerduty_service.foo (prepare state)
2021/06/30 12:02:11 DestroyEdgeTransformer: pruning unused resource node pagerduty_service_event_rule.foo (prepare state)
--- PASS: TestAccPagerDutyServiceEventRule_Basic (18.97s)
=== RUN   TestAccPagerDutyServiceEventRule_MultipleRules
2021/06/30 12:02:26 DestroyEdgeTransformer: pruning unused resource node pagerduty_service_event_rule.foo (prepare state)
2021/06/30 12:02:26 DestroyEdgeTransformer: pruning unused resource node pagerduty_service_event_rule.bar (prepare state)
2021/06/30 12:02:26 DestroyEdgeTransformer: pruning unused resource node pagerduty_user.foo (prepare state)
2021/06/30 12:02:26 DestroyEdgeTransformer: pruning unused resource node pagerduty_escalation_policy.foo (prepare state)
2021/06/30 12:02:26 DestroyEdgeTransformer: pruning unused resource node pagerduty_service.foo (prepare state)
2021/06/30 12:02:26 DestroyEdgeTransformer: pruning unused resource node pagerduty_service_event_rule.baz (prepare state)
--- PASS: TestAccPagerDutyServiceEventRule_MultipleRules (16.71s)
=== RUN   TestAccPagerDutyServiceIntegration_Basic
2021/06/30 12:02:51 DestroyEdgeTransformer: pruning unused resource node pagerduty_service.foo (prepare state)
2021/06/30 12:02:51 DestroyEdgeTransformer: pruning unused resource node pagerduty_user.foo (prepare state)
2021/06/30 12:02:51 DestroyEdgeTransformer: pruning unused resource node pagerduty_escalation_policy.foo (prepare state)
2021/06/30 12:02:51 DestroyEdgeTransformer: pruning unused resource node pagerduty_service_integration.foo (prepare state)
2021/06/30 12:02:51 DestroyEdgeTransformer: pruning unused resource node data.pagerduty_vendor.datadog (prepare state)
--- PASS: TestAccPagerDutyServiceIntegration_Basic (24.52s)
=== RUN   TestAccPagerDutyServiceIntegrationGeneric_Basic
2021/06/30 12:03:12 DestroyEdgeTransformer: pruning unused resource node pagerduty_escalation_policy.foo (prepare state)
2021/06/30 12:03:12 DestroyEdgeTransformer: pruning unused resource node pagerduty_user.foo (prepare state)
2021/06/30 12:03:12 DestroyEdgeTransformer: pruning unused resource node pagerduty_service.foo (prepare state)
2021/06/30 12:03:12 DestroyEdgeTransformer: pruning unused resource node pagerduty_service_integration.foo (prepare state)
--- PASS: TestAccPagerDutyServiceIntegrationGeneric_Basic (20.44s)
=== RUN   TestAccPagerDutyService_Basic
2021/06/30 12:03:33 DestroyEdgeTransformer: pruning unused resource node pagerduty_user.foo (prepare state)
2021/06/30 12:03:33 DestroyEdgeTransformer: pruning unused resource node pagerduty_escalation_policy.foo (prepare state)
2021/06/30 12:03:33 DestroyEdgeTransformer: pruning unused resource node pagerduty_service.foo (prepare state)
--- PASS: TestAccPagerDutyService_Basic (20.74s)
=== RUN   TestAccPagerDutyService_AlertGrouping
2021/06/30 12:03:51 DestroyEdgeTransformer: pruning unused resource node pagerduty_user.foo (prepare state)
2021/06/30 12:03:51 DestroyEdgeTransformer: pruning unused resource node pagerduty_escalation_policy.foo (prepare state)
2021/06/30 12:03:51 DestroyEdgeTransformer: pruning unused resource node pagerduty_service.foo (prepare state)
--- PASS: TestAccPagerDutyService_AlertGrouping (17.16s)
=== RUN   TestAccPagerDutyService_AlertContentGrouping
2021/06/30 12:04:03 DestroyEdgeTransformer: pruning unused resource node pagerduty_service.foo (prepare state)
2021/06/30 12:04:03 DestroyEdgeTransformer: pruning unused resource node pagerduty_user.foo (prepare state)
2021/06/30 12:04:03 DestroyEdgeTransformer: pruning unused resource node pagerduty_escalation_policy.foo (prepare state)
--- PASS: TestAccPagerDutyService_AlertContentGrouping (12.71s)
=== RUN   TestAccPagerDutyService_BasicWithIncidentUrgencyRules
2021/06/30 12:04:25 DestroyEdgeTransformer: pruning unused resource node pagerduty_service.foo (prepare state)
2021/06/30 12:04:25 DestroyEdgeTransformer: pruning unused resource node pagerduty_user.foo (prepare state)
2021/06/30 12:04:25 DestroyEdgeTransformer: pruning unused resource node pagerduty_escalation_policy.foo (prepare state)
--- PASS: TestAccPagerDutyService_BasicWithIncidentUrgencyRules (21.25s)
=== RUN   TestAccPagerDutyService_FromBasicToCustomIncidentUrgencyRules
2021/06/30 12:04:42 DestroyEdgeTransformer: pruning unused resource node pagerduty_user.foo (prepare state)
2021/06/30 12:04:42 DestroyEdgeTransformer: pruning unused resource node pagerduty_escalation_policy.foo (prepare state)
2021/06/30 12:04:42 DestroyEdgeTransformer: pruning unused resource node pagerduty_service.foo (prepare state)
--- PASS: TestAccPagerDutyService_FromBasicToCustomIncidentUrgencyRules (16.80s)
=== RUN   TestAccPagerDutyService_SupportHoursChange
2021/06/30 12:04:59 DestroyEdgeTransformer: pruning unused resource node pagerduty_user.foo (prepare state)
2021/06/30 12:04:59 DestroyEdgeTransformer: pruning unused resource node pagerduty_escalation_policy.foo (prepare state)
2021/06/30 12:04:59 DestroyEdgeTransformer: pruning unused resource node pagerduty_service.foo (prepare state)
--- PASS: TestAccPagerDutyService_SupportHoursChange (17.47s)
PASS
ok  	github.com/terraform-providers/terraform-provider-pagerduty/pagerduty	266.535s

**Comment by NargiT** [comment]
any update on this ?

**Review by stmcallister — APPROVED** [review]
Looks good! 🎉

**Comment by NargiT** [comment]
what is the release policy ? I would like to use this feature so hard :pray:

**Pull request merged**
