### PR TITLE
Fix create race condition

### PR DESCRIPTION
**Pull request by eric-spence-code**
Addressing race conditions on creates where resources immediately GET after creating #273 .  Similar to GH-274 but addressing it by allowing callers to pass in a different error callback based on what the invoking function wants the error behavior to be.

### CODE REVIEW

**Comment by eric-spence-code** [comment]
@stmcallister Apologies for the direct ping but I see you are a consistent contributor to this repo. Are there any guidelines on how to get reviewers added to this PR and any next steps to get this one merged. Thanks!

**Comment by eric-spence-code** [comment]
@drastawi I noticed that you have also been involved in some prs recently. Am I missing anything to get this work reviewed?

**Comment by stmcallister** [comment]
@eric-spence-code sorry for letting this sit so long! can you resolve the conflicts? I'll be sure to review it soon after the conflicts are resolved. Thanks!

**Comment by ericSpence** [comment]
@stmcallister no problem! I will try to get to that today or tomorrow :D

**Comment by eric-spence-code** [comment]
@stmcallister all good! I will get those conflicts resolved. Anything else needed for this pr to get merged

**Comment by stmcallister** [comment]
@eric-spence-code as far as i can tell, without testing, it looks pretty good!

**Comment by stmcallister** [comment]
@eric-spence-code were you ready for me to test? I saw some activity on the PR and gave it another try but ran into some issues with this code in the `fetch` functions. So, maybe you're not ready? 😅 

What I'm seeing is this code:
```
client := meta.(*pagerduty.Client)
```
Throws an error `panic: interface conversion: interface {} is *pagerduty.Config, not *pagerduty.Client`.

The other functions are building `client` with `client, _ := meta.(*Config).Client()`.  

Is there advantage to using `meta.(*pagerduty.Client)` I'm not seeing?

**Comment by eric-spence-code** [comment]
@stmcallister nah its just a bad merge. I will update them all to use the same client constructor.

**Comment by stmcallister** [comment]
@eric-spence-code also, can you merge in the latest master as well? I'm still getting conflicts with recent changes to master.

**Comment by eric-spence-code** [comment]
@stmcallister just pulled in upstream and I am not seeing any conflicts. Are you saying merge conflicts or failing tests?

**Review by stmcallister — APPROVED** [review]
That works! Thanks, @eric-spence-code ! 👍

**Pull request merged**
