### PR TITLE
`slack_connection`: remove state on 404

### PR DESCRIPTION
**Pull request by bendrucker**
This PR modifies the `pagerduty_slack_connection` resource to removes connections that are gone (404) when read. All other errors should be reported to the user and abort the plan. I've borrowed the implementation already used in other resources, e.g., `pagerduty_service`.

### Current Behavior

When a Slack connection is removed outside of Terraform, the plan fails at refresh:

```
Error: GET API call to https://app.pagerduty.com/integration-slack/workspaces/T03PBSXSU/connections/PX75ILE failed 404 Not Found. Code: 0, Errors: <nil>, Message: Not Found
```

### Expected Behavior

Terraform should successfully refresh/plan, removing the resource from state and planning to re-create it if it's still declared in the configuration.

### CODE REVIEW

**Comment by bendrucker** [comment]
I'll go ahead and run the acceptance tests tomorrow to verify this and can also add an acceptance test that exercises this error handling branch. Also noticing some hardcoding of Slack IDs in the test file which I can get coverted to env vars.

**Comment by bendrucker** [comment]
Confirming that acceptance tests pass:

```
Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run TestAccPagerDutySlackConnection -timeout 120m
?   	github.com/terraform-providers/terraform-provider-pagerduty	[no test files]
=== RUN   TestAccPagerDutySlackConnection_import
--- PASS: TestAccPagerDutySlackConnection_import (68.13s)
=== RUN   TestAccPagerDutySlackConnectionTeam_import
--- PASS: TestAccPagerDutySlackConnectionTeam_import (23.10s)
=== RUN   TestAccPagerDutySlackConnection_Basic
--- PASS: TestAccPagerDutySlackConnection_Basic (38.08s)
=== RUN   TestAccPagerDutySlackConnection_Team
--- PASS: TestAccPagerDutySlackConnection_Team (30.38s)
=== RUN   TestAccPagerDutySlackConnection_Envar
--- PASS: TestAccPagerDutySlackConnection_Envar (18.12s)
PASS
ok  	github.com/terraform-providers/terraform-provider-pagerduty/pagerduty	178.053s
```

Ended up just modifying the hardcoded values rather than updating tests.

**Comment by bendrucker** [comment]
Hey @stmcallister just wanted to re-raise this bug fix. For users who have issues with a Slack workspace connection requiring removal, there's a fair amount of `state rm` required without this change.

**Comment by ElGrecode** [comment]
This looks good to me! Any expectation on when we can see this merged in @imjaroiswebdev ?

`state rm` shouldn't be the expectation here

**Pull request closed without merging**
