### PR TITLE
GitHub action bumps

### PR DESCRIPTION
**Pull request by magnetikonline**
- Bumping some GitHub Actions to `@v3` versions.
- Added build badge for Test workflow to `README.md`
- Added friendly names for workflows (`Release` and `Test`)

### CODE REVIEW

**Comment by magnetikonline** [comment]
ping @alenapan 👋

**Comment by alenapan** [comment]
@stmcallister delegating this one to you since I'm not the repo owner :)

**Comment by magnetikonline** [comment]
Thx @alenapan

**Comment by magnetikonline** [comment]
Small bump @stmcallister 👍

**Comment by magnetikonline** [comment]
Maybe @jedelson-pagerduty ?

**Comment by magnetikonline** [comment]
Ping @stmcallister 😄

**Comment by magnetikonline** [comment]
Maybe something @imjaroiswebdev can look at?

**Comment by magnetikonline** [comment]
Moved over to Opsgenie since cost of PagerDuty was getting absurd. Probably not a bad thing as review of these PRs is terrible as best... 🤷

**Pull request closed without merging**
