### PR TITLE
Add email_filters to pagerduty_service_integration

### PR DESCRIPTION
**Pull request by tibibo**
Require this PR — https://github.com/heimweh/go-pagerduty/pull/31

### CODE REVIEW

**Comment by drastawi** [comment]
The dependency PR had been merged already, so we should be good to go on this one. @tibibo are you still planning to merge this in?

**Comment by bohdanborovskyi-ma** [comment]
@tibibo @drastawi @stmcallister Can we get this merged?
Right now, it's blocking us from fully adopting the IaC approach for managing resources on PD platform.

We're used to invoke local-exec provisioner with custom shell script (which adds email_filters to the integrations via API). That's inconvenient method from several aspects, however it's still better than changing these rules for 100+ integrations manually.

**Comment by stmcallister** [comment]
Looks like there are conflicts on this RP. @tibibo would you be able to address these so we can merge?

**Comment by stmcallister** [comment]
Closing this PR in favor of #468 which uses the same code on top of the current version of master.

**Pull request closed without merging**
